export { default as CustomerCarousel } from "./customer/carousel";
// export { default as CustomerSlider } from "./customer/slider";
// export { default as CustomerCategories } from "./customer/categories";
// export { default as CustomerCategoryCard } from "./customer/category card";
export { default as CustomerProductCard } from "./customer/product-card";
export { default as CustomerProductSlider } from "./customer/product-slider";
export { default as CustomerProductVariant } from "./customer/product-variant";
export { default as CustomerQuantityInputGroup } from "./customer/quantity-input-group";
export { default as CustomerRating } from "./customer/rating";
export { default as CustomerRatingFull } from "./customer/rating-full";
